language: cpp
dist: trusty
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - libllvm6.0
      - llvm-6.0
      - llvm-6.0-dev
      - llvm-6.0-doc
      - llvm-6.0-examples
      - llvm-6.0-runtime
      - clang-6.0
      - clang-tools-6.0
      - clang-6.0-doc
      - libclang-common-6.0-dev
      - libclang-6.0-dev
      - libclang1-6.0
      - clang-format-6.0
      - python-clang-6.0
      - lldb-6.0
      - lld-6.0
env:
  - LLVM_DIR=/usr/lib/llvm-6.0
install:
  - make tools
script:
  - make -j